import { Deal, Stage } from '../types';

export const MOCK_DEALS: Deal[] = [
  {
    "id": 2447,
    "title": "Regiane Do Rocio",
    "value": 4635.0,
    "currency": "BRL",
    "add_time": "2023-08-19T19:49:42Z",
    "status": "won",
    "pipeline_id": 7,
    "stage_id": 67, // Sales Pipeline - Won
    "won_time": "2023-09-05T03:00:00Z",
    "lost_time": null,
    "close_time": "2023-09-05T03:00:00Z",
    "owner_id": 1,
    "owner_name": "Maikon P.",
    "lost_reason": null,
    "products_count": 1,
    "source": "Linkedin"
  },
  {
    "id": 2475,
    "title": "Anderson Bahia",
    "value": 165.0,
    "currency": "BRL",
    "add_time": "2023-09-11T21:41:39Z",
    "status": "won",
    "pipeline_id": 7,
    "stage_id": 67,
    "won_time": "2023-09-26T03:00:00Z",
    "lost_time": null,
    "close_time": "2023-09-26T03:00:00Z",
    "owner_id": 1,
    "owner_name": "Maikon P.",
    "lost_reason": null,
    "products_count": 2,
    "source": "Lead Inbound"
  },
  {
    "id": 2391,
    "title": "Anderlon Junqueira",
    "value": 1500.0, 
    "currency": "BRL",
    "add_time": "2023-12-29T16:52:21Z",
    "status": "lost",
    "pipeline_id": 7,
    "stage_id": 64, // Oportunidade Gerada (Loss at start)
    "won_time": null,
    "lost_time": "2024-01-01T03:00:00Z",
    "close_time": "2024-01-01T03:00:00Z",
    "owner_id": 2,
    "owner_name": "Cristopher",
    "lost_reason": "Reprovado | Sem perfil",
    "products_count": 1,
    "source": "Retomada"
  },
  {
    "id": 2696,
    "title": "Francisco Gomes",
    "value": 1068.0,
    "currency": "BRL",
    "add_time": "2023-08-09T19:07:32Z",
    "status": "won",
    "pipeline_id": 7,
    "stage_id": 67,
    "won_time": "2023-11-13T03:00:00Z",
    "lost_time": null,
    "close_time": "2023-11-13T03:00:00Z",
    "owner_id": 1,
    "owner_name": "Maikon P.",
    "lost_reason": null,
    "products_count": 1,
    "source": "Sem valor"
  },
  {
      "id": 2614,
      "title": "Diego Da Silva",
      "value": 5000.0,
      "currency": "BRL",
      "status": "open",
      "pipeline_id": 7,
      "stage_id": 65, // Proposta Apresentada
      "add_time": "2023-10-02T00:19:34Z",
      "won_time": null,
      "lost_time": null,
      "close_time": null,
      "owner_id": 1,
      "owner_name": "Maikon P.",
      "lost_reason": null,
      "products_count": 3,
      "source": "Linkedin"
  },
    {
      "id": 2615,
      "title": "Diogo Denes",
      "value": 12000.0,
      "currency": "BRL",
      "status": "open",
      "pipeline_id": 7,
      "stage_id": 66, // Em negociação
      "add_time": "2023-10-02T00:19:34Z",
      "won_time": null,
      "lost_time": null,
      "close_time": null,
      "owner_id": 2,
      "owner_name": "Cristopher",
      "lost_reason": null,
      "products_count": 1,
      "source": "Lead Inbound"
  },
  {
    "id": 2700,
    "title": "Maria Silva",
    "value": 3200.0,
    "currency": "BRL",
    "status": "open",
    "pipeline_id": 7,
    "stage_id": 64, // Oportunidade
    "add_time": "2023-10-05T10:00:00Z",
    "won_time": null,
    "lost_time": null,
    "close_time": null,
    "owner_id": 1,
    "owner_name": "Maikon P.",
    "lost_reason": null,
    "products_count": 1,
    "source": "Lead Inbound"
  },
  {
    "id": 2701,
    "title": "João Souza",
    "value": 2100.0,
    "currency": "BRL",
    "status": "open",
    "pipeline_id": 7,
    "stage_id": 68, // Aguardando Pagamento
    "add_time": "2023-10-06T14:00:00Z",
    "won_time": null,
    "lost_time": null,
    "close_time": null,
    "owner_id": 1,
    "owner_name": "Maikon P.",
    "lost_reason": null,
    "products_count": 1,
    "source": "Linkedin"
  }
];

export const MOCK_STAGES: Stage[] = [
    { id: 64, name: "Oportunidade Gerada", pipeline_id: 7, pipeline_name: "Sales | AdvEasy", order_nr: 1 },
    { id: 65, name: "Proposta Apresentada", pipeline_id: 7, pipeline_name: "Sales | AdvEasy", order_nr: 2 },
    { id: 66, name: "Em negociação", pipeline_id: 7, pipeline_name: "Sales | AdvEasy", order_nr: 3 },
    { id: 68, name: "Aguardando Pagamento", pipeline_id: 7, pipeline_name: "Sales | AdvEasy", order_nr: 4 },
    { id: 67, name: "Ganho", pipeline_id: 7, pipeline_name: "Sales | AdvEasy", order_nr: 5 },
];
